"""Synthetic retail product catalog generator."""

from synthetic_retail_generator.generator import (
    DEFAULT_CONFIG_PATH,
    ConfigLoadError,
    GenerationContext,
    GenerationConfig,
    allocate_category_counts,
    catalog_to_json,
    generate_catalog,
    generate_product,
    load_generation_config,
    write_catalog,
)
from synthetic_retail_generator.models import (
    CATEGORY_MODEL_BY_CODE,
    CATEGORY_TITLE_BY_CODE,
    CategoryCode,
    ProductCatalog,
    ProductModel,
    ProductVariant,
)
from synthetic_retail_generator.schema_reader import (
    ProductCatalogSchema,
    ProductDefinitionSpec,
    PropertySpec,
    SchemaContractError,
    SchemaLoadError,
    TypeMapping,
    load_product_catalog_schema,
    map_json_schema_type,
    parse_product_catalog_schema,
)

__all__ = [
    "CATEGORY_MODEL_BY_CODE",
    "CATEGORY_TITLE_BY_CODE",
    "CategoryCode",
    "ConfigLoadError",
    "DEFAULT_CONFIG_PATH",
    "GenerationContext",
    "GenerationConfig",
    "ProductCatalog",
    "ProductCatalogSchema",
    "ProductDefinitionSpec",
    "ProductModel",
    "ProductVariant",
    "PropertySpec",
    "SchemaContractError",
    "SchemaLoadError",
    "TypeMapping",
    "allocate_category_counts",
    "catalog_to_json",
    "generate_catalog",
    "generate_product",
    "load_generation_config",
    "load_product_catalog_schema",
    "map_json_schema_type",
    "parse_product_catalog_schema",
    "write_catalog",
]
